# Generated by Django 5.0.7 on 2024-08-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_details_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_published',
            new_name='is_published',
        ),
    ]
