# Generated by Django 5.0.7 on 2024-09-24 13:38

import apps.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_meta_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.ImageField(blank=True, null=True, upload_to=apps.product.models.featured_image_path),
        ),
    ]
