# Generated by Django 5.0.7 on 2024-08-28 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
        ('review', '0003_alter_review_unique_together_review_order_line_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order_line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitem_reviews', to='order.orderlineitem'),
        ),
    ]
