# Generated by Django 5.0.7 on 2024-09-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_comment_alter_review_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='text',
        ),
    ]
