# Generated by Django 5.0.7 on 2024-09-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_review_comment_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
