# Generated by Django 5.0.7 on 2024-08-22 14:01

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_user_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('complete', 'Complete'), ('processing', 'Processing')], default='processing', max_length=20),
        ),
    ]
